--- make/makefile.orig	2020-06-12 20:25:55.880629867 -0500
+++ make/makefile	2020-06-12 20:27:25.645408629 -0500
@@ -42,15 +42,15 @@
 .SUFFIXES: .c .cpp .f .f90 .F90 .fpp .o
 
 # Define the Fortran compile flags
-FC = gfortran
-FFLAGS = -O2 -fbacktrace -Bstatic -D_WIN32 -MMD -cpp 
+#FC = gfortran
+#FFLAGS = -O2 -fbacktrace -Bstatic -D_WIN32 -MMD -cpp 
 
 # Define the C compile flags
-CC = gcc
-CFLAGS = -O2 -Bstatic -D_UF -MMD -cpp 
+#CC = gcc
+#CFLAGS = -O2 -Bstatic -D_UF -MMD -cpp 
 
 # Define the libraries
-SYSLIBS = -lgfortran -lm 
+#SYSLIBS = -lgfortran -lm 
 
 OBJECTS = \
 $(OBJDIR)/OpenSpec.o \
