--- make/makefile.orig	2020-02-14 11:29:56.912351904 -0500
+++ make/makefile	2020-02-14 11:30:29.936409577 -0500
@@ -42,15 +42,15 @@
 .SUFFIXES: .c .cpp .f .f90 .F90 .fpp .o
 
 # Define the Fortran compile flags
-FC = gfortran
-FFLAGS = -O2 -fbacktrace 
+#FC = gfortran
+#FFLAGS = -O2 -fbacktrace 
 
 # Define the C compile flags
-CC = gcc
-CFLAGS = -O2 -D_UF 
+#CC = gcc
+#CFLAGS = -O2 -D_UF 
 
 # Define the libraries
-SYSLIBS = 
+#SYSLIBS = 
 
 OBJECTS = \
 $(OBJDIR)/kind.o \
