{% set name = "modflow6" %}
{% set version = "6.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MODFLOW-USGS/modflow6/releases/download/{{ version }}/mf{{ version }}_linux.zip
  sha256: 98158735102cd3e98106df8962d215bd5107556e53e067ac791dcdc1f801e7c5

build:
  number: 1

requirements:
  build:
    - {{ compiler('fortran') }}   # [not win]
    - {{ stdlib("c") }}           # [not win]
    - gfortran                    # [win]
    - meson
    - ninja
  run:
    - libgfortran                 # [win]

test:
  commands:
    - mf6 --help

about:
  home: https://www.usgs.gov/software/modflow-6-usgs-modular-hydrologic-model
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE.md
  summary: USGS Modular Hydrologic Model
  description: |
    MODFLOW 6 is an object-oriented program and framework developed to provide
    a platform for supporting multiple models and multiple types of models
    within the same simulation. Within this framework, a regional-scale
    groundwater model may be coupled with multiple local-scale groundwater
    models. Or, a groundwater flow model could be coupled to a groundwater
    transport model of a single solute species.
  doc_url: https://water.usgs.gov/water-resources/software/MODFLOW-6/mf6io_{{ version }}.pdf
  dev_url: https://github.com/MODFLOW-USGS/modflow6

extra:
  recipe-maintainers:
    - mwtoews
    - jdhughes-usgs
    - Hofer-Julian
    - scopatz
    - scharlton2
