{% set name = "modflow6" %}
{% set version = "6.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MODFLOW-USGS/modflow6/releases/download/{{ version }}/mf{{ version }}.zip
  sha256: d9f1d17a41b7517c329994a2f21dd1d5006f04e6c5611702167fa9a945ebc82c

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - meson
    - ninja

test:
  commands:
    - mf6 --help

about:
  home: https://www.usgs.gov/software/modflow-6-usgs-modular-hydrologic-model
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE.md
  summary: Open-source groundwater flow model
  doc_url: https://water.usgs.gov/water-resources/software/MODFLOW-6/mf6io_{{ version }}.pdf
  dev_url: https://github.com/MODFLOW-USGS/modflow6

extra:
  recipe-maintainers:
    - jdhughes-usgs
    - Hofer-Julian
    - scopatz
