{% set name = "modflow6" %}
{% set version = "6.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MODFLOW-USGS/modflow6/releases/download/{{ version }}/mf{{ version }}.zip
  sha256: 64323dc8d3684b5faac916e396f81ea41fe013b8390a187f35eac32a81179e37
  patches:
    # use inherited environment variables
    - makefile.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

test:
  commands:
    - mf6 --help

about:
  home: https://www.usgs.gov/software/modflow-6-usgs-modular-hydrologic-model
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE.md
  summary: Open-source groundwater flow model
  doc_url: https://water.usgs.gov/water-resources/software/MODFLOW-6/mf6io_{{ version }}.pdf
  dev_url: https://github.com/MODFLOW-USGS/modflow6

extra:
  recipe-maintainers:
    - scopatz
